version: v1
build:
  # recommendation: use the official maven repo if you want to change runtime version: https://hub.docker.com/_/maven
  image: docker.io/maven:3.9.1-eclipse-temurin-17
  # definitions of environment variables that will be used in all stages of your pipeline
  environmentVariables: []
    #- key: variable1
    #  value: value1
    #- key: variable2
    #  value: value2
    #- key: variable3
    #  value: value3
  pipelines:
    release:
      pipeline: java-maven-lib